/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PatternsIndexRouteImport } from './routes/patterns.index'
import { Route as PatternsSlugRouteImport } from './routes/patterns.$slug'
import { Route as ProblemIdRouteImport } from './routes/problem.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PatternsIndexRoute = PatternsIndexRouteImport.update({
  id: '/patterns/',
  path: '/patterns/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatternsSlugRoute = PatternsSlugRouteImport.update({
  id: '/patterns/$slug',
  path: '/patterns/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemIdRoute = ProblemIdRouteImport.update({
  id: '/problem/$id',
  path: '/problem/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/patterns/$slug': typeof PatternsSlugRoute
  '/problem/$id': typeof ProblemIdRoute
  '/patterns/': typeof PatternsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/patterns/$slug': typeof PatternsSlugRoute
  '/problem/$id': typeof ProblemIdRoute
  '/patterns': typeof PatternsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/patterns/$slug': typeof PatternsSlugRoute
  '/problem/$id': typeof ProblemIdRoute
  '/patterns/': typeof PatternsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/profile'
    | '/settings'
    | '/patterns/$slug'
    | '/problem/$id'
    | '/patterns/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/profile'
    | '/settings'
    | '/patterns/$slug'
    | '/problem/$id'
    | '/patterns'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/profile'
    | '/settings'
    | '/patterns/$slug'
    | '/problem/$id'
    | '/patterns/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  PatternsSlugRoute: typeof PatternsSlugRoute
  ProblemIdRoute: typeof ProblemIdRoute
  PatternsIndexRoute: typeof PatternsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patterns/': {
      id: '/patterns/'
      path: '/patterns'
      fullPath: '/patterns/'
      preLoaderRoute: typeof PatternsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patterns/$slug': {
      id: '/patterns/$slug'
      path: '/patterns/$slug'
      fullPath: '/patterns/$slug'
      preLoaderRoute: typeof PatternsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problem/$id': {
      id: '/problem/$id'
      path: '/problem/$id'
      fullPath: '/problem/$id'
      preLoaderRoute: typeof ProblemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  PatternsSlugRoute: PatternsSlugRoute,
  ProblemIdRoute: ProblemIdRoute,
  PatternsIndexRoute: PatternsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
